import './contacts/index';
import './menu/index';
import './pages/index';
import './pages/pages/mainPage/index';
import './pages/pages/projectsPage/index';
import './pages/pages/videoPage/index';
import './pages/pages/galleriesPage/index';
import './pages/pages/servicesPage/index';
import './footer/index';